# Generated by Django 4.0.2 on 2022-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='spent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='goal',
            field=models.FloatField(default=0),
        ),
    ]
