# Generated by Django 4.0.2 on 2022-02-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_subcategory_spent_alter_subcategory_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SubCategories'},
        ),
    ]
