# Generated by Django 4.0.2 on 2022-02-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_month_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('February', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'June'), ('6', 'July'), ('7', 'August'), ('8', 'September'), ('9', 'October'), ('10', 'November'), ('11', 'December')], max_length=200),
        ),
    ]
