# Generated by Django 4.0.2 on 2022-02-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
            preserve_default=False,
        ),
    ]
