# Generated by Django 4.0.2 on 2022-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_month_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('01 January', 'January'), ('02 February', 'February222'), ('03 March', 'March'), ('04 April', 'April'), ('05 May', 'May'), ('06 June', 'June'), ('07 July', 'July'), ('08 August', 'August'), ('09 September', 'September'), ('10 October', 'October'), ('11 November', 'November'), ('12 December', 'December')], max_length=200),
        ),
    ]
